### ISSUE TITLE
PAGE NOT FOUND

### ISSUE THREAD

**Issue by mkc0602** [inkonchain/docs#191]
Accessing this page https://docs.inkonchain.com/build/tutorials/deploy-a-smart-contract-using/foundry throws Page Not Found

**Comment by mkc0602** [comment]
This is the tutorials page accessed from the main page https://docs.inkonchain.com/

**Comment by johubkra** [comment]
thank you, fixing

**Comment by johubkra** [comment]
https://github.com/inkonchain/docs/pull/205
