### ISSUE TITLE
Smart Contract Error Link

### ISSUE THREAD

**Issue by Isoo2025** [inkonchain/docs#192]
Tutorial link for smart contract deployment not functioning. 

The link below not working
https://docs.inkonchain.com/build/tutorials/deploy-a-smart-contract-using/foundry

![Screenshot_20241102-162650_Kiwi Browser](https://github.com/user-attachments/assets/6c9b5615-7f73-4f09-b24f-4fe6c69c3613)

**Comment by johubkra** [comment]
thx fixed https://github.com/inkonchain/docs/pull/205
