### ISSUE TITLE
why publish contract for remix it return this

### ISSUE THREAD

**Issue by fall-g** [inkonchain/docs#225]
No compatible chain found for the selected EVM version.
Consider opening an issue to update our internal store with your desired chainId.

**Comment by johubkra** [comment]
@fall-g in Remix you should use the provider injected by your web3 wallet e.g. Metamask: 
<img width="288" alt="image" src="https://github.com/user-attachments/assets/bb3ba367-cd35-47c3-9016-a69b70f62f14">

Info on how to add Ink to your web3 wallet can be found [here](https://docs.inkonchain.com/quick-start/get-connected).

Closing issue as not specific to Ink documentation.
